// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFp7qzkO9HTBdtNZP6m-O1z3Rr7azmzQ',
    appId: '1:277858909:web:b040bf3180e5db1dbc5bb4',
    messagingSenderId: '277858909',
    projectId: 'reactflutter-3aa72',
    authDomain: 'reactflutter-3aa72.firebaseapp.com',
    storageBucket: 'reactflutter-3aa72.appspot.com',
    measurementId: 'G-FQJ4ZF6SZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkXy26a9LB79B7EWJG9_qWC2gneK5OSrM',
    appId: '1:277858909:android:5b5eab737eaf846cbc5bb4',
    messagingSenderId: '277858909',
    projectId: 'reactflutter-3aa72',
    storageBucket: 'reactflutter-3aa72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApAqFC9hxW5R3HRMgjivoUpBvzBqXivrQ',
    appId: '1:277858909:ios:90fda55c1a7cdb97bc5bb4',
    messagingSenderId: '277858909',
    projectId: 'reactflutter-3aa72',
    storageBucket: 'reactflutter-3aa72.appspot.com',
    iosBundleId: 'com.example.commentsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApAqFC9hxW5R3HRMgjivoUpBvzBqXivrQ',
    appId: '1:277858909:ios:90fda55c1a7cdb97bc5bb4',
    messagingSenderId: '277858909',
    projectId: 'reactflutter-3aa72',
    storageBucket: 'reactflutter-3aa72.appspot.com',
    iosBundleId: 'com.example.commentsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFp7qzkO9HTBdtNZP6m-O1z3Rr7azmzQ',
    appId: '1:277858909:web:4e36fca42f2ccb51bc5bb4',
    messagingSenderId: '277858909',
    projectId: 'reactflutter-3aa72',
    authDomain: 'reactflutter-3aa72.firebaseapp.com',
    storageBucket: 'reactflutter-3aa72.appspot.com',
    measurementId: 'G-JYMNRP5532',
  );
}
